export const MESSAGE = {
  ATTACK: 'ATTACK',
  UNDER_ATTACK: 'UNDER_ATTACK',
  UPDATE_USER_LIST: 'UPDATE_USER_LIST',
  LOGIN: 'LOGIN',
  CHALLENGE: 'CHALLENGE',
  CHALLENGE_CANCEL: 'CHALLENGE_CANCEL',
  CHALLENGE_RESPONSE: 'CHALLENGE_RESPONSE',
}

export const SERVER = {
  URL: 'http://localhost:3000'
}

export const STATE = {
  LOGIN: 'LOGIN',
  USER_SELECT: 'USER_SELECT',
  CHALLENGING: 'CHALLENGING',
  IN_GAME: 'IN_GAME'
}