export const MESSAGE = {
  // STATE USER SELECT
  US_LOGIN: 'LOGIN',
  US_CHALLENGE: 'US_CHALLENGE',
  US_CHALLENGE_CANCEL: 'US_CHALLENGE_CANCEL',
  US_CHALLENGE_RESPONSE: 'US_CHALLENGE_RESPONSE',
  US_UPDATE_USER_LIST: 'US_UPDATE_USER_LIST',

  // STATE IN GAME
  IG_ATTACK: 'IG_ATTACK',
  IG_UNDER_ATTACK: 'IG_UNDER_ATTACK',
}

export const SERVER = {
  URL: 'http://localhost:3000'
}

export const STATE = {
  LOGIN: 'LOGIN',
  USER_SELECT: 'USER_SELECT',
  IN_GAME: 'IN_GAME'
}